### ISSUE TITLE
Replace Flask-RQ with Flask-RQ2

### ISSUE THREAD

**Issue by jace** [hasgeek/hgapp#11]
The projects are distinct. [Flask-RQ2](https://github.com/rq/Flask-RQ2) is the official, maintained extension, but it's not 100% compatible. All apps need to switch. Since they can be installed in parallel, this does not need to be an all-at-once switch.

**Comment by jace** [comment]
@iambibhas this has been pending for a while. Change needed in Funnel, Lastuser, Hasjob, Boxoffice and here.

**Comment by iambibhas** [comment]
@jace this hgapp repo has no code that uses RQ. It's just mentioned in requirements and settings. That's all.

**Comment by jace** [comment]
It does have `rq.sh`. We clone this repo when making a new app, so it needs to have the boilerplate for RQ.
